-- 코드를 입력하세요
SELECT i.FOOD_TYPE, i.REST_ID, i.REST_NAME, f.FAVORITES
FROM (SELECT FOOD_TYPE, max(FAVORITES) as "FAVORITES" FROM REST_INFO GROUP BY FOOD_TYPE) f JOIN 
REST_INFO i
ON f.FOOD_TYPE = i.FOOD_TYPE AND f.FAVORITES = i.FAVORITES
ORDER BY f.FOOD_TYPE DESC