-- 코드를 입력하세요
SELECT i.FOOD_TYPE, i.REST_ID, i.REST_NAME, i.FAVORITES
FROM (SELECT FOOD_TYPE, max(FAVORITES) as "FAVORITES" 
      FROM REST_INFO 
      GROUP BY FOOD_TYPE) s JOIN REST_INFO i
      ON s.FAVORITES = i.FAVORITES and s.FOOD_TYPE = i.FOOD_TYPE
ORDER BY i.FOOD_TYPE DESC