-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, b.TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) as "TOTAL_SALES" FROM USED_GOODS_BOARD
     WHERE STATUS= 'DONE'
     GROUP BY WRITER_ID
     HAVING TOTAL_SALES >= 700000
     ) b JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
ORDER BY b.TOTAL_SALES
     