-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, sum(PRICE) as "TOTAL_SALES"
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u 
ON (WRITER_ID = USER_ID and STATUS = "DONE")
GROUP BY USER_ID, NICKNAME
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES