-- 코드를 작성해주세요
SELECT e.EMP_NO, e.EMP_NAME, 
CASE 
    WHEN SCORE >= 96 THEN 'S'
    WHEN SCORE >= 90 THEN 'A'
    WHEN SCORE >= 80 THEN 'B'
    ELSE 'C'
END 
as "GRADE",
CASE 
    WHEN g.SCORE >= 96 THEN e.SAL * 0.2
    WHEN g.SCORE >= 90 THEN e.SAL * 0.15
    WHEN g.SCORE >= 80 THEN e.SAL * 0.1
    ELSE 0
END
as "BONUS"
FROM HR_EMPLOYEES e JOIN (
    SELECT EMP_NO, avg(score) as "SCORE"
    FROM HR_GRADE
    GROUP BY EMP_NO
) g ON e.EMP_NO = g.EMP_NO
ORDER BY e.EMP_NO

