-- 코드를 입력하세요
SELECT p.MEMBER_NAME, r.REVIEW_TEXT, r.REVIEW_DATE
FROM MEMBER_PROFILE p JOIN REST_REVIEW r 
ON p.MEMBER_ID = r.MEMBER_ID
WHERE p.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING count(*) = (
        SELECT max(cnt)
        FROM (SELECT count(*) as "cnt" from REST_REVIEW GROUP BY MEMBER_ID ) t
    )
)
ORDER BY r.REVIEW_DATE, REVIEW_TEXT