-- 코드를 입력하세요
SELECT p.MEMBER_NAME, r2.REVIEW_TEXT, r2.REVIEW_DATE
FROM (
    (
    (SELECT count(REVIEW_ID) as "cnt", MEMBER_ID
    FROM REST_REVIEW
    group by MEMBER_ID
    ORDER BY cnt DESC
    limit 1
) r join MEMBER_PROFILE p 
on r.MEMBER_ID = p.MEMBER_ID
) 
JOIN REST_REVIEW r2
ON r2.MEMBER_ID = r.MEMBER_ID
)
ORDER BY r2.REVIEW_DATE, r2.REVIEW_TEXT