-- 코드를 입력하세요
SELECT MCDP_CD AS "진료과코드", COUNT(*) as "5월예약건수"
FROM (SELECT APNT_YMD FROM APPOINTMENT WHERE year(APNT_YMD) = '2022' and month(APNT_YMD) = '5') d JOIN APPOINTMENT a ON a.APNT_YMD = d.APNT_YMD 
GROUP BY MCDP_CD
ORDER BY COUNT(*), MCDP_CD