-- 코드를 작성해주세요
SELECT e.YEAR, e.SIZE -d.SIZE_OF_COLONY as "YEAR_DEV", d.id
FROM (SELECT year(DIFFERENTIATION_DATE) as "YEAR", max(SIZE_OF_COLONY) as "SIZE" FROM ECOLI_DATA GROUP BY YEAR) e JOIN ECOLI_DATA d
ON e.YEAR = year(d.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV