SELECT g.SCORE, g.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM (SELECT EMP_NO, sum(SCORE) as "SCORE" FROM HR_GRADE GROUP BY EMP_NO ) g JOIN HR_EMPLOYEES e 
ON g.EMP_NO = e.EMP_NO
ORDER BY SCORE DESC
limit 1

