-- 코드를 작성해주세요
SELECT d.DEPT_ID, d.DEPT_NAME_EN, e.AVG_SAL
FROM (
    SELECT DEPT_ID, ROUND(AVG(SAL)) as "AVG_SAL"
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) e JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
ORDER BY e.AVG_SAL DESC