-- 코드를 입력하세요
SELECT c.CATEGORY, c.MAX_PRICE, f.PRODUCT_NAME
FROM (SELECT CATEGORY, max(price) as "MAX_PRICE"
      FROM FOOD_PRODUCT 
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
      GROUP BY CATEGORY
     ) c JOIN FOOD_PRODUCT f
     ON c.CATEGORY = f.CATEGORY and c.MAX_PRICE = f.PRICE
ORDER BY c.MAX_PRICE DESC